config/routes.rb
Rails.application.routes.draw do
  devise_for :users , :controllers => {:registrations => "user/registrations"}
  root 'welcome#index'
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'stock_search', to: "stocks#search"
  get 'my_friends', to: "users#my_friends"
  get 'search_friends', to: "users#search"
  post 'add_friend', to: "users#add_friend"




  resources :users , only: [:show]
  resources 'user_stocks', only: [:create, :destroy]
  resources :friendships

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend , :class_name => 'User'
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users ,through: :user_stocks

  def self.new_form_lookup(ticker_symbol)
#begin .... rescue Exception => e : ratowanie przed errror
  begin
   looked_up_stock = StockQuote::Stock.quote(ticker_symbol)
   #price = looked_up_stock.latest_price
   #symbol = looked_up_stock.symbol
   #name = looked_up_stock.company_name
   new(name: looked_up_stock.company_name, ticker: looked_up_stock.symbol, last_price: looked_up_stock.latest_price )
 rescue Exception => e
  p e.inspect
  return nil
  end
end

def self.find_by_ticker(ticker_symbol)
  where(ticker: ticker_symbol).first
  end


end

app/models/user.rb
 class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships



  def full_name
    #return "#{first_name} #{last_name}".strip if (first_name || last_name)
    #"anonymous"
      if first_name
        return "#{first_name}".strip
      else
        return "anonymous"
      end


  end


  def stock_already_added?(ticker_symbol)
    stock = Stock.find_by_ticker(ticker_symbol)
    return false unless stock
    user_stocks.where(stock_id: stock.id).exists?
  end

  def under_stock_limit?
    (user_stocks.count < 10)
  end


  def can_add_stock?(ticker_symbol)
    under_stock_limit? && !stock_already_added?(ticker_symbol)
  end

  def self.search(param)
    param.strip!
    param.downcase!
    to_send_back = (first_name_mateches(param) + last_name_matches(param)+email_name_matches(param)).uniq
    return nil unless to_send_back
    to_send_back
  end

  def self.first_name_mateches(param)
    mateches('first_name', param)
  end

  def self.last_name_matches(param)
    mateches('last_name', param)
  end

  def self.email_name_matches(param)
    mateches('email', param)
  end

  def self.mateches(field_name, param)
      User.where("#{field_name} like?", "%#{param}%")
  end

  def except_current_user(users)
    users.reject { |user| user.id == self.id }
  end

  def not_freinds_with?(friend_id)
    friendships.where(friend_id: friend_id).count < 1
  end


end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!

end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def destroy
    @friendship = current_user.friendships.where(friend_id: params[:id]).first
    @friendship.destroy
    flash[:notice]= "successfully deleted user"
    redirect_to my_friends_path
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController

def search

  if params[:stock].blank?
    flash.now[:danger] = "You have entered an empety string"
  else
    @stock = Stock.new_form_lookup(params[:stock])
    flash.now[:danger] = "You have entered incorrect stock symbol" unless @stock
  end
    respond_to do |format|
      format.js {render partial: 'users/results'}
  end
end







#def search
#if params[:stock].present?
#  @stock = Stock.new_form_lookup(params[:stock])
#  if @stock
#    respond_to do |format|
#    format.js {render partial: 'users/results'}
#  end
#  else
#    respond_to do |format|
#    flash.now[:danger] = "you have entered  an incorrect symbol"
#    format.js {render partial: 'users/results'}
#  end
#  end
#else
#  respond_to do |format|
#  flash.now[:danger] = "you have entered empety search string"
#  format.js {render partial: 'users/results'}
#end
#end
#end


end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name , :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController

def create
  stock = Stock.find_by_ticker(params[:stock_ticker])
  if stock.blank?
    stock = Stock.new_form_lookup(params[:stock_ticker])
    stock.save
  end
  @user_stock = UserStock.create(user:current_user, stock: stock)
  flash[:success] = "Stock #{@user_stock.stock.name} was successfylyu added to portfolio"
  redirect_to my_portfolio_path
end


def destroy
  stock = Stock.find(params[:id])
  @user_stock = UserStock.where(user_id: current_user, stock_id: stock.id).first
  @user_stock.destroy
  flash[:success] = "Stack successfully removed from portfolio"
  redirect_to my_portfolio_path
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def my_portfolio
  @user = current_user
  @user_stocks = current_user.stocks
end

def my_friends
  @friendships = current_user.friends
end

def add_friend
  @friend = User.find(params[:friend])
  current_user.friendships.build(friend_id: @friend.id)

  if current_user.save
    flash[:success] = "firend was succsesfully added"
  else
    flash[:danger] = "errorr kurwa"
  end
  redirect_to my_friends_path
end


def search

    if params[:search_param].blank?
    flash.now[:danger] = "You have entered an empety string"
  else
    @users = User.search(params[:search_param])
    @users = current_user.except_current_user(@users)
    flash.now[:danger] = "You have entered incorrect user name" if @users.blank?
  end
    respond_to do |format|
      format.js {render partial: 'friends/results'}
  end
end

def show
  @user = User.find(params[:id])
  @user_stocks = @user.stocks
end




end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/friends/_lookup.html.haml
%h1{align:"center"} My Friend
%h3 Search Friend's
.friend-lookup
  = form_tag search_friends_path ,remote: true, method: :get, id: "friend-lookup-form" do
    .form-group.row.no-padding
      .cal-md-10
        =text_field_tag :search_param, params[:search_param], placeholder: "stock ticker symbol", autofocus: true, class: "form-control search-box input-lg"
      .col-md-2
        =button_tag(type: :submit, class: "btn btn-lg btn-success") do
          %i{class: "fa fa-search"} Look up a friend
    .well
    #results
      = render 'friends/results'

app/views/friends/_results.html.haml
- if params[:action] == "search"
  .results-block
    = bootstrap_flash

- if @users
  #friend-lookup-results.well.results-block.col-md-10
    %table.search-results-table.col-md-12
      %tbody
        -@users.each do |user|
          %tr
            %td
              %strong Name:
              =user.full_name
            %td
              %strong  Email:
              =user.email
            %td
              %strong Profile:
              =link_to "view Profile", user_path(user), class: "btn btn-xs btn-success"
              - if current_user.not_freinds_with?(user.id)
                =link_to "Add my friend" ,add_friend_path(user: current_user, friend: user), class: "btn btn-xs btn-success", method: :post
              -else
                %span.label.label-primary
                  you are already fiernds

app/views/friends/_results.js.erb
$('#results').html("<%= j (render 'friends/results.html') %>")

app/views/layouts/_navigation.html.haml
.navbar.navbar-default.navbar-static-top
  .container
    - if current_user
      %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      .navbar-brand
        = link_to "FinanceTracker", root_path
      .navbar-collapse.collapse.navbar-responsive-collapse
        %ul.nav.navbar-nav
          %li= link_to "My portfolio", my_portfolio_path
          %li= link_to "my profile", edit_user_registration_path(current_user)
          %li= link_to "my friends",  my_friends_path
        %ul.nav.navbar-right.col-md-4
          %li.col-md-8
            %i.fa.fa-user
            -if current_user.full_name.present?
              = current_user.full_name
            -else
              = current_user.email
          %li.col-md-4.logout
            = link_to "Logout", destroy_user_session_path, class: "btn btn-xs btn-danger", method: :Delete, data: {confirm: "are you sure?"}

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "FinanceTracker"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"


  %body
    = render 'layouts/navigation'
    .container
      .row
        .col-lg-12
          = bootstrap_flash
          = yield
-#        .col-lg-3
-#          .well.sidebar-nav
-#            %h3 Sidebar
-#            %ul.nav.nav-list
-#              %li.nav-header Sidebar
-#              %li= link_to "Link 1", "/path1"
-#              %li= link_to "Link 2", "/path2"
-#              %li= link_to "Link 3", "/path3"
    %footer
      %p &copy; Company 2018

app/views/stocks/_list.html.haml
%table.table.table-striped
  %thead
    %tr
      %th
        Name
      %th
        Symbol
      %th
        Current Price
      - if @user.id == current_user.id
        %th
          Actions
  %tboady
    - @user_stocks.each do |user_stock|
      %tr
        %td
          = user_stock.name
        %td
          = user_stock.ticker
        %td
          = user_stock.last_price
        %td
          - if @user.id == current_user.id
            = link_to "Delet this stock", user_stock_path(user_stock), method: :delete, data: {confirm: "are you sure?"}, class: "btn btn-danger btn-xs"

app/views/users/_results.html.haml
- if params[:action] == "search"
  .results-block
    = bootstrap_flash
-if @stock
  %strong Symbol
  = @stock.ticker
  %strong Name:
  = @stock.name
  %strong Price:
  = @stock.last_price
  -if current_user.can_add_stock?(@stock.ticker)
    = link_to "add to my stocks", user_stocks_path(user: current_user, stock_ticker: @stock.ticker), class: "btn btn-xs btn-success", method: :post
  -else
    %span.label.label-default
      Stock cannot be added becouse you have arleady added
      - if !current_user.under_stock_limit?
        10 stock
      - if current_user.stock_already_added?(@stock.ticker)
        this stock

app/views/users/_results.js.erb
$('#results').html("<%= j (render 'users/results.html') %>")

app/views/users/my_friends.html.haml
= render 'friends/lookup'
-if @friendships.size > 0
  %h4 My friends
  %table.table.table-striped
    %thead
      %tr
        %th
          Name
        %th
          email
    %tboady
      -@friendships.each do |friend|
        %tr
          %td
            = friend.full_name
          %td
            = friend.email
          %td
            =link_to "view firend", user_path(friend), class: "btn btn-primery"
            =link_to "remove friend", friendship_path(friend), method: :delete, data: {confirm: "are yoy sure?"}, class: "btn btn-ls btn-danger"
-else
  .row.col-lg-12
    %p.lead
    You don have any friends

app/views/users/my_portfolio.html.haml
%h1{align:"center"} My Portfolio
%h3 Search for stock
.stock-lookup
  = form_tag stock_search_path ,remote: true, method: :get, id: "stock-lookup-form" do
    .form-group.row.no-padding
      .cal-md-10
        =text_field_tag :stock, params[:stock], placeholder: "stock ticker symbol", autofocus: true, class: "form-control search-box input-lg"
      .col-md-2
        =button_tag(type: :submit, class: "btn btn-lg btn-success") do
          %i{class: "fa fa-search"} Look up a stock
    .well
      #results
        = render 'users/results'
    = render 'stocks/list'

app/views/users/show.html.haml
%h3
User details
%h5
  User name:
  = @user.full_name
%h5
  Email:
  = @user.email

- if @user_stocks.count > 0
  =render 'stocks/list'
-else
  %p.lead
    This user isn't tracking any stocks
= link_to "back", my_friends_path, class: "btn btn-cs btn-primary"

app/views/welcome/index.html.haml
%h1 Welcome to the homepage finance tracker